apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-demo
  strategy:
    canary:
      canaryService: go-demo-canary   # Canary service
      stableService: go-demo          # Stable service
      steps:
        - setWeight: 20
        - pause: {}                   # Pause indefinitely (wait for Jenkins approval)
  template:
    metadata:
      labels:
        app: go-demo
    spec:
      containers:
        - name: app
          image: sharmachandan487/go-demo:latest
          ports:
            - containerPort: 8085
          env:
            - name: VERSION
              value: "v1"
