apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-demo
  strategy:
    canary:
      canaryService: go-demo-canary
      stableService: go-demo
      steps:
        - setWeight: 20
        - pause: {}   # pause indefinitely
  template:
    metadata:
      labels:
        app: go-demo
    spec:
      containers:
      - name: app
        image: sharmachandan487/go-demo:${VERSION}   # 🔹 dynamically injected
        ports:
        - containerPort: 8085
