apiVersion: v1
kind: Service
metadata:
  name: go-demo
spec:
  selector:
    app: go-demo
  ports:
    - port: 80
      targetPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: go-demo-canary
spec:
  selector:
    app: go-demo
  ports:
    - port: 80
      targetPort: 8085
