apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: demo-app
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/istio-ingress
  http:
    - route:
        - destination:
            host: demo-app
            subset: stable
          weight: 80
        - destination:
            host: demo-app
            subset: canary
          weight: 20
